name: "gsora's place"
description: A random-generated blog
meta_description: "Personal blog of Gianguido (gsora) Sorà"

highlighter: rouge
logo: false
paginate: 4
baseurl: /
domain_name: 'http://blog.gsora.xyz'
google_analytics: 'UA-69845983-1'

gems: [jekyll-paginate]
