name: "gsora's place"
description: A random-generated-content blog
meta_description: "Personal blog of Gianguido (gsora) Sora`, with a great punchline too."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 4
baseurl: /
domain_name: 'http://blog.gsora.xyz'
google_analytics: 'UA-69845983-1'

# Details for the RSS feed generator
url:            'blog.gsora.xyz'
author:         'Gianguido (gsora) Sora`'
permalink: /:year/:month/:day/:title 
about: false
