# Permalinks
permalink:           pretty

# Setup
title:               gsora's place
tagline:             about me 
url:                 http://blog.gsora.xyz
paginate:            4
baseurl:             ""
permalink:           :year/:title

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Gianguido (gsora) Sorà
  url:               https://twitter.com/gsora_
  email:             gsora@protonmail.com

# gsora personalizations
analytics_id: 'UA-69845983-1'
        
# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
