name: "plk's place"
description: A random-generated-content blog
meta_description: "Personal blog of Gianguido (plk) Sora`, with a great punchline too."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 4
baseurl: /
domain_name: 'http://blog.urandom.me'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'blog.urandom.me'
author:         'Gianguido (plk) Sora`'
permalink: /:year/:month/:day/:title 
about: false
